--
-- PostgreSQL database dump
--

\restrict jxqq48NtOxBvIjphfUbVItk0NWRvyblhPNCkOEu8HqJtPpYKH1q58zDW7BxnNdh

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: friends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friends (
    user_id integer NOT NULL,
    friend_id integer NOT NULL,
    status text
);


--
-- Name: gameplayers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gameplayers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    total_score integer,
    placement integer,
    status text
);


--
-- Name: gamerounds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gamerounds (
    id integer NOT NULL,
    game_id integer NOT NULL,
    location_id integer NOT NULL,
    round_number integer,
    time_limit integer,
    started_at timestamp without time zone,
    ended_at timestamp without time zone
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    host_user_id integer NOT NULL,
    mode text,
    is_invite_only boolean,
    round_count integer,
    time_limit integer,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    status text
);


--
-- Name: guesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guesses (
    id bigint NOT NULL,
    round_id integer NOT NULL,
    user_id integer NOT NULL,
    guess_latitude double precision,
    guess_longitude double precision,
    distance_km integer,
    guess_time integer,
    score integer
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id integer NOT NULL,
    filename text NOT NULL,
    name text NOT NULL,
    latitude double precision,
    longitude double precision,
    difficulty text,
    average_score integer
);


--
-- Name: COLUMN locations.difficulty; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.locations.difficulty IS 'easy, medium, hard';


--
-- Name: COLUMN locations.average_score; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.locations.average_score IS 'average of all user scores on this location';


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.locations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    token text NOT NULL,
    login text NOT NULL,
    email text,
    github_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer CONSTRAINT user_id_not_null NOT NULL,
    username text CONSTRAINT user_username_not_null NOT NULL,
    email text CONSTRAINT user_email_not_null NOT NULL,
    password text CONSTRAINT user_password_not_null NOT NULL,
    profile_picture bigint,
    wins integer DEFAULT 0,
    total_score integer DEFAULT 0,
    total_games integer DEFAULT 0,
    highest_score integer DEFAULT 0,
    csrf_token text,
    session_token text,
    created_at timestamp without time zone,
    last_login timestamp without time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);


--
-- Name: friends friends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT friends_pkey PRIMARY KEY (user_id, friend_id);


--
-- Name: gameplayers gameplayers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gameplayers
    ADD CONSTRAINT gameplayers_pkey PRIMARY KEY (id);


--
-- Name: gamerounds gamerounds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gamerounds
    ADD CONSTRAINT gamerounds_pkey PRIMARY KEY (id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: guesses guesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT guesses_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (token);


--
-- Name: users user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: friends friend_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT friend_id FOREIGN KEY (friend_id) REFERENCES public.users(id);


--
-- Name: gamerounds game_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gamerounds
    ADD CONSTRAINT game_id FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: games host_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT host_user_id FOREIGN KEY (host_user_id) REFERENCES public.users(id);


--
-- Name: gamerounds location_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gamerounds
    ADD CONSTRAINT location_id FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: guesses round_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT round_id FOREIGN KEY (round_id) REFERENCES public.gamerounds(id);


--
-- Name: friends user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: gameplayers user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gameplayers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: guesses user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guesses
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict jxqq48NtOxBvIjphfUbVItk0NWRvyblhPNCkOEu8HqJtPpYKH1q58zDW7BxnNdh

